workflows:
  android-build:
    name: Build & Release Android (NyanTV)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - keystore_credentials
        - app_env_vars
      vars:
        FLUTTER_VERSION: "3.32.8"
        JAVA_VERSION: "17"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
    scripts:
      - name: Set up Java
        script: |
          jdk-switch --version $JAVA_VERSION
      - name: Set up Flutter
        script: |
          flutter channel stable
          flutter upgrade $FLUTTER_VERSION
      - name: Setup App Environment (.env)
        script: |
          cat > .env << EOF
          AL_CLIENT_ID=$AL_CLIENT_ID
          AL_CLIENT_SECRET=$AL_CLIENT_SECRET
          CALLBACK_SCHEME=$CALLBACK_SCHEME
          EOF
      - name: Setup Android Keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/nyantv.jks
          cat > android/key.properties << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=nyantv.jks
          EOF
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Generate Native Splash
        script: |
          dart run flutter_native_splash:create
      - name: Build Android APK
        script: |
          flutter build apk \
            --split-per-abi \
            --target-platform android-arm \
            --release \
            --no-tree-shake-icons \
            --build-number=$BUILD_NUMBER
      - name: Rename APK
        script: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/NyanTV-Android-armeabi-v7a.apk
    artifacts:
      - build/app/outputs/flutter-apk/NyanTV-Android-armeabi-v7a.apk